#!/usr/bin/env node
// Downloads the site's web fonts from Google Fonts into assets/fonts and writes assets/css/fonts.css
// (self-hosted: no third-party request at runtime, same unicode-range subsetting).
import fs from 'node:fs'; import path from 'node:path';
const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0 Safari/537.36';
const families = ['Source+Serif+4:ital,wght@0,400..600;1,400', 'Inter:wght@400..600'];
const keep = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);
let css = '/* Self-hosted web fonts (subset per unicode-range). Generated by tools/fetch-fonts.mjs */\n';
for (const fam of families) {
  const res = await fetch(`https://fonts.googleapis.com/css2?family=${fam}&display=swap`, { headers: { 'User-Agent': UA } });
  const text = await res.text();
  const blocks = text.split('@font-face').slice(1);
  let prevSubset = '';
  for (const raw of text.split(/(?=\/\* [a-z-]+ \*\/)/)) {
    const m = raw.match(/^\/\* ([a-z-]+) \*\//); if (!m) continue; const subset = m[1]; if (!keep.has(subset)) continue;
    const family = raw.match(/font-family: '([^']+)'/)[1];
    const style = raw.match(/font-style: (\w+)/)[1];
    const weight = raw.match(/font-weight: ([\d ]+)/)[1];
    const url = raw.match(/url\(([^)]+)\)/)[1];
    const range = raw.match(/unicode-range: ([^;]+);/)[1];
    const slug = family.toLowerCase().replace(/\s+/g, '-');
    const file = `${slug}-${style}-${subset}.woff2`;
    const out = path.join(ROOT, 'assets/fonts', file);
    if (!fs.existsSync(out)) { const buf = Buffer.from(await (await fetch(url)).arrayBuffer()); fs.writeFileSync(out, buf); }
    const extra = family === 'Source Serif 4' ? '  font-variation-settings: normal;\n' : '';
    css += `@font-face {\n  font-family: '${family}';\n  font-style: ${style};\n  font-weight: ${weight};\n  font-display: swap;\n  src: url(/assets/fonts/${file}) format('woff2');\n  unicode-range: ${range};\n}\n`;
    console.log(file, fs.statSync(out).size, 'bytes');
  }
}
css += `
/* Fallback faces with metric overrides (measured in tools/fetch-fonts.mjs notes) so text keeps its
   size and line height while the web fonts load, which keeps layout shift near zero. */
@font-face { font-family: 'Source Serif 4 Fallback'; src: local('Georgia'); size-adjust: 107.02%; ascent-override: 96.8%; descent-override: 31.3%; line-gap-override: 0%; }
@font-face { font-family: 'Source Serif 4 Fallback'; font-style: italic; src: local('Georgia Italic'), local('Georgia-Italic'); size-adjust: 96.98%; ascent-override: 106.8%; descent-override: 34.5%; line-gap-override: 0%; }
@font-face { font-family: 'Inter Fallback'; src: local('Arial'), local('Helvetica'); size-adjust: 107.07%; ascent-override: 90.5%; descent-override: 22.5%; line-gap-override: 0%; }
`;
fs.writeFileSync(path.join(ROOT, 'assets/css/fonts.css'), css);
console.log('wrote assets/css/fonts.css');
